# Generated by Django 3.2.7 on 2021-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210913_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
