# Generated by Django 3.2.7 on 2021-09-13 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_baseusermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
