# Generated by Django 3.2.7 on 2021-09-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_baseusermodel_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='clerk',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.clerk'),
        ),
    ]
