# Generated by Django 3.2.7 on 2021-09-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_branch_clerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='clerk',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.clerk'),
        ),
    ]
