# Generated by Django 3.2.7 on 2021-09-14 07:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_branch_clerk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.branch')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=255)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='core.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('amount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)])),
                ('type', models.CharField(choices=[('12', '12'), ('24', '24')], default='12', max_length=255)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
