TRANSACTION_TYPE_DEPOSIT = 'deposit'
TRANSACTION_TYPE_WITHDRAWAL = 'withdrawal'
TRANSACTION_TYPE_TRANSFER = 'transfer'

TRANSACTION_TYPE_CHOICES = (
    (TRANSACTION_TYPE_DEPOSIT, 'Deposit'),
    (TRANSACTION_TYPE_WITHDRAWAL, 'Withdrawal'),
    (TRANSACTION_TYPE_TRANSFER, 'Transfer')
)

LOAN_TYPE_12_MONTHS = '12'
LOAN_TYPE_24_MONTHS = '24'

LOAN_TYPE_CHOICES = (
    (LOAN_TYPE_12_MONTHS, '12'),
    (LOAN_TYPE_24_MONTHS, '24')
)
